markdown:         kramdown
permalink:        /posts/:title/

title:            "Gaozhipeng's Blog"    
description:      "选择一种你自己的生活"
highlighter:      rouge
author:
    name:      gaozp 
    key:       gaozp
